steps:
  # Deploy the function
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - processImageAndData
      - --runtime=nodejs18
      - --trigger=http
      - --allow-unauthenticated
      - --entry-point=processImageAndData
      - --source=.
      - --region=us-central1
      - --memory=512MB
      - --timeout=540s
